public enum CharPartType : byte
{
    Skin            = 0,
    Eye             = 1,
    Pupil           = 2,
    Mouth           = 3,
    Nose            = 4,
    Ear             = 5,
    Brow            = 6,
    Hair            = 7,
    Beard           = 8,
    Shirt           = 9,
    Pants           = 10,
    Socks           = 11,
    Underwear       = 12,
    Accessory       = 13,
    Belt            = 14,

    Skin_B          = 64,
    Eye_B           = 65,
    Pupil_B         = 66,
    Mouth_B         = 67,
    Nose_B          = 68,
    Ear_B           = 69,
    Brow_B          = 70,
    Hair_B          = 71,
    Beard_B         = 72,
    Shirt_B         = 73,
    Pants_B         = 74,
    Socks_B         = 75,
    Underwear_B     = 76,
    Accessory_B     = 77,
    Belt_B          = 78,

    Skin_C          = 128,
    Eye_C           = 129,
    Pupil_C         = 130,
    Mouth_C         = 131,
    Nose_C          = 132,
    Ear_C           = 133,
    Brow_C          = 134,
    Hair_C          = 135,
    Beard_C         = 136,
    Shirt_C         = 137,
    Pants_C         = 138,
    Socks_C         = 139,
    Underwear_C     = 140,
    Accessory_C     = 141,
    Belt_C          = 142,

    Skin_D          = 192,
    Eye_D           = 193,
    Pupil_D         = 194,
    Mouth_D         = 195,
    Nose_D          = 196,
    Ear_D           = 197,
    Brow_D          = 198,
    Hair_D          = 199,
    Beard_D         = 200,
    Shirt_D         = 201,
    Pants_D         = 202,
    Socks_D         = 203,
    Underwear_D     = 204,
    Accessory_D     = 205,
    Belt_D          = 206,

}
